import {
  ATIS,
  BeaconLights,
  Flaps,
  FlightPlan,
  FuelQuantity,
  LandingLights,
  MasterSwitch,
  NavLights,
  NoSmoking,
  ParkingBrakes,
  PushbackClearance,
  SeatBelts,
  Spoilers,
  StrobeLights,
  Throttle,
} from './controlSettings';

const BEFORE_START = [
  MasterSwitch.ON,
  ParkingBrakes.SET,
  Throttle.IDLE,
  Spoilers.OFF,
  Flaps.RETRACTED,
  NoSmoking.ON,
  FlightPlan.FILED,
  FuelQuantity.CHECK,
  ATIS.CHECK,
  SeatBelts.ON,
  NavLights.ON,
  BeaconLights.OFF,
  StrobeLights.OFF,
  LandingLights.OFF,
  PushbackClearance.RECEIVED,
];
